README.md
pull_request_template.md

- Add naming convention code snippet to `README.md`
- Update dependency list in `README.md`
- Minor formatting improvements to `README.md`
- Remove a line in `pull_request_template.md`
Documentation update only.

Update Readme/Minor tweak to pull_request_template

---

README.md

Add contributers section to README

Add contributers section to README

---

README.md

Edited the readme, moved Jest to the dev dependencies section.
Documentation only

edited readme, moved Jest to dev dependencies

---

.gitignore
README.md
server/api/routes.js
server/app.js
server/package-lock.json
server/package.json
server/server.js

Back end setup, local db setup, scafold routing setup

---

server/api/controllers/user_controller.js
server/api/models/user.js
server/api/routes.js

Created folder structure for the server, created basic user schema with mongoose, created post route handler.

able to register user

---

README.md
server/api/controllers/user_controller.js
server/api/models/user.js
server/api/routes.js
server/api/utils/auth.js
server/api/utils/landing.html
server/api/utils/passport.js
server/app.js
server/package-lock.json
server/package.json

Local strategy established, jwt strategy done. Can create user, login user, protected routes and authenticate a token

Em backend setup

---

server/api/models/note.js
server/api/models/user.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Note Schema 

---

server/api/models/user.js

- Add `async` keyword to `getNotes` function to fix error.
- Renamed `getNotes` to `get_notes` to conform to existing naming convention
Tested locally.

Bugfix: Add `async` for `getNotes` function

---

client/src/Components/Settings/ChangeEmail.js
client/src/Components/Settings/ChangeEmail.test.js
client/src/Components/Settings/ChangePassword.js
client/src/Components/Settings/ChangePassword.test.js
client/src/Components/Settings/Preferences.test.js
client/src/Components/Settings/Settings.js
client/src/Components/Settings/Settings.test.js

Implements functionality that lets you change your email and password from the Settings panel.
Manually tested; added some basic smoke tests for the components

ChangeEmail/ChangePassword - front end

---

client/src/Components/Note/Note.css
client/src/Components/Note/Note.js
client/src/Components/Note/Note.less
client/src/Components/Note/NoteEdit.js
client/src/Components/Note/NoteView.js

Broke down notes component into smaller components
Created styling with Less
Added click-text-to-edit feature
Tested it locally through the browser

frontend notes restructure + styling

---

Procfile
__tests__/server.test.js
api/models/user.js
api/utils/auth.js
api/utils/passport.js
app.js
package-lock.json
package.json

- Use an in-memory mongodb instance for tests
- Use a fresh server instance for each test
- Ignore tests in `client` folder when running `npm test` in root folder.
- Improve some tests
- Improve logging
- Code cleanup
**NOTE**: New dependency was added so running `npm i` inside the root folder is required for tests to run properly.
- All new and existing tests are passing.
- Application was tested manually and continues to work as expected.

Backend testing improvements

---

__tests__/server.test.js
api/controllers/user_controller.js
api/routes.js
api/utils/auth.js
api/utils/passport.js

- Add a `/api/get_user/:id` GET route that takes a token in the headers and returns the associated user
- Tested manually with Postman
- Added tests in `server.test.js` that check if route works with a valid token sent in headers or fails with invalid/missing token

Backend `get_user` route

---

.gitignore
api/models/user.js
app.js

- Hotfix for syntax errors 
- Add package-lock.json to .gitignore
- Tested manually
- Existing automated tests all pass

Fix syntax error and ignore package-lock.json

---

client/src/Components/Dashboard/Dashboard.css
client/src/Components/Dashboard/Dashboard.js
client/src/Components/Dashboard/Dashboard.less
client/src/Components/Map/Map.js
client/src/Components/Nav/Nav.js
client/src/Components/SearchCountry/SearchCountry.js
client/src/Components/SearchCountry/SearchCountry.test.js

- Add functionality that allows you to search for a country and it will be highlighted on the map
- Move Search component from Nav to Dashboard
**IMPORTANT NOTE!!!**: This will eventually need to get refactored to avoid using a deprecated lifecycle method (`componentWillReceiveProps`), as well as an async/await hack to get the functionality working as expected (see comments in `Map.js`).
- Added smoke test for SearchCountry component

Search for a country functionality

---

api/models/user.js
client/package.json
client/src/Components/CountryCard/Card.js
client/src/Components/CountryCard/CardHeader.js
client/src/Components/Map/Map.js

Country name and flag displaying on the card

Em clicked country

---

client/src/Components/Map/Map.js

fixed the ocean problem
fixes issue #62 

Bugfix: Clicking Marker on Non-land Spaces Throws Error (issue #62)

---

client/src/Components/Dashboard/Dashboard.js
client/src/Components/Settings/Settings.css
client/src/Components/Settings/Settings.js
client/src/Components/Settings/Settings.less

- Settings panel now slides in and out instead of disappearing immediately on close. 
- All existing test pass

Settings component slides in and out

---

client/src/Components/Legend/Legend.css
client/src/Components/Legend/Legend.js
client/src/Components/Legend/Legend.less

Adds an extra category to the Legend (named 'No Interest' for now).

Add extra category to Legend

---

api/controllers/user_controller.js
client/src/AppContext.js
client/src/Components/Dashboard/Dashboard.js
client/src/Components/Map/Map.js
client/src/Components/Map/Map.test.js
client/src/Components/Nav/Nav.js
client/src/Components/SearchCountry/SearchCountry.js
client/src/utils.js

- Refactor to move `currentCountry` to AppContext
- `currentCountry` now stores country code and country info
- Add helper functions to `utils.js` and import/use in the relevant files
- Code cleanup
fixes issues #69 and #57 
- Tested manually to ensure all functionality still works
- All existing test pass

Move currentCountry to AppContext

---

client/src/AppContext.js

Handles rejection errors in async await

async await handle rejection

---

client/src/AppContext.js
client/src/Components/CountryCard/Card.js
client/src/Components/Dashboard/Dashboard.js
client/src/Components/Friends/FriendList.js
client/src/Components/Map/Map.js
client/src/utils.js

- Move geolocation code to `AppContext`
- Move `clearLocalStorage` to `utils.js`
- Fix for user data not being stored properly in `AppContext` when user visits site after previously logging in.
- `FriendList` now pulls data from the `social` field of the `user` object in `AppContext`
- Map marker is now a dedicated marker to represent `userPosition`:
- Pulls location from `userPosition` set in `AppContext`
- Dragging is disabled
- Popup is disabled (original code is still there in comments for reference)
- All existing test pass

Move geolocation to AppContext/Map marker represents userPosition

---

client/src/AppContext.js
client/src/Components/Friends/FriendList.js
client/src/Components/Map/Map.js

- Fix for user data not being stored on app state when user has a valid
token and user in localStorage.
- Get friendlist info from `social` field on user object
- Disable marker popup
- Tested manually
- All exisiting tests pass

Bug fixes for retrieving user data + friendList

---

client/src/Components/CountryCard/Card.js

- Modify `Card.js` to send the entire `user` object to `FriendList` so it
doesn't cause crash.
`FriendList` may not need the entire `user` object, but sending it anyway for
convenience. We can change this later when we know for sure what props
it needs.
- Manually tested

Bugfix: Clicking causes app to crash

---

README.md
api/routes.js
api/utils/landing.html
package.json
server.js

This should have everything required to deploy the entire app with a `git push heroku master` command.
- Add `heroku-postbuild` script to root folders `package.json` that builds the React app when deploying
- Specify node and npm versions in `engines` field of root folders `package.json`
- Add route to serve up static React build files at site's root endpoint
- Update README to include deployment instructions
- Tested manually in browser/localhost
- Deployed this branch to heroku and tested in browser
- All existing tests continue to pass

Heroku deployment frontend setup

---

README.md
api/controllers/user_controller.js
api/routes.js
api/utils/landing.html
client/src/AppContext.js
client/src/Components/Dashboard/Dashboard.js
client/src/Components/Map/Map.js
client/src/Components/Map/countryStyles.js
package.json
server.js

- Render a geojson layer for each country on the `user` object
- geojson layer uses style corresponding to `status_code`
- Add styles for each `status_code`
- Add `countryStyles.js` to store styles for countries' geojson layers
- Bug fix for user data not correctly being stored upon sign in
**NOTE**: I had to manually add some countries to a model saved in my local mongodb in order to test this. You will have to do the same thing in order to get the individual countries showing up. Just make sure it conforms to the format specified in the `User` schema.

Map layer per country on user object

---

client/src/Components/LandingPage/LogInBay.js

Modal no longer throwing error in console.
Fixes #39 

Issue: Sign Up Modal

---

api/controllers/statusController.js
client/src/AppContext.js
client/src/Components/BorderBay/BorderBay.js
client/src/Components/CountryPanel/CountryPanel.js
server.js

- Moving the slider on a country's card updates it's status and colors it the appropriate color

Slider functionality and update country status

---

client/src/AppContext.js
client/src/Components/Map/Map.js

- New mapTile is rendered immediately after applying preferences

Handle theme change

---

client/src/Components/CountryBorder/CountryBorder.js

quick fix, clears the border if you select the ocean

clear the draw if no country selected

---

__tests__/server.test.js
api/controllers/user_controller.js

- Add tests for `/country_status` route
- Improve naming and formatting of current tests
- Save an `initialTestUser` to DB before each test
- Clear the DB after each test
**NOTE**: `server.test.js` file is starting to get long and unwieldy. We should, at some point, consider breaking them up into multiple files and refactoring to eliminate duplicated code by making better use of beforeEach/afterEach.
Tested with tests... Everything is passing and producing the intended results.

Tests for `/country_status`

---

client/src/AppContext.js

- Fixes issue where map would flash when slider changes due to clearing user on state before setting it again
- Update comments
Fixes #108 

Fix #108: Map flashes on slider change

---

__tests__/server.test.js
api/controllers/statusController.js
api/models/user.js
api/routes.js

- Add a `/api/country_notes` route that updates a users notes for a particular country
- Convert `/api/country_status` to use async/await
- Add tests for `/api/country_notes` 
- Tested manually with rest client
- Added automated tests to `server.test.js`

Backend route for update notes; handle_status uses async/await

---

client/src/Components/Settings/ChangeEmail.js
client/src/Components/Settings/ChangeEmailError.js
client/src/Components/Settings/ChangePassword.js
client/src/Components/Settings/ChangePasswordError.js

Currently includes local error handling
For EmailChange: 
-checks for completion of fields
-checks for valid password (>5 char)
For PasswordChange:
-checks for completion of fields
-checks for password match
-checks for valid new password (>5)
-checks for valid old password (>5)
Todo:
need regex for email validation
none yet

local error handling -- settings

---

__tests__/server.test.js
api/controllers/user_controller.js
api/utils/auth.js
api/utils/passport.js

- Add email validation when creating new user and updating existing user's email
- Improve error handling when changing password
- Improve error handling when changing preferences
- Clean up code and improve comments
- Add/updates tests to check for specific error cases
- Additional tests added to check error handling
- All existing tests continue to pass

Backend settings error handling

---

api/routes.js
api/utils/passport.js
api/utils/privacy_policy.html
client/src/Components/LandingPage/LogInBay.js

- Generated a boilerplate privacy policy and added to an html file
- Add route to serve html file (need this to provide the facebook app with a valid privacy policy link)
- Tested manually
- All existing tests continue to pass

Add privacy policy

---

client/package.json
client/src/Components/CountryBorder/CountryBorder.js
client/src/Components/Friends/FriendList.js
client/src/Components/LandingPage/FailedSignUpPopUp.js
client/src/Components/LandingPage/LandingPage.js
client/src/Components/LandingPage/LogInBay.js
client/src/Components/Map/Map.js
client/src/Components/Nav/Nav.js
client/src/Components/Note/Note.js
client/src/Components/SearchCountry/SearchCountry.js
client/src/Components/Settings/ChangeEmail.js
client/src/Components/Settings/ChangeEmailError.js
client/src/Components/Settings/ChangePassword.js
client/src/Components/Settings/ChangePasswordError.js
client/src/Components/Settings/Preferences.js
client/src/Components/Settings/Settings.js

Installed prop-types npm package as react docs suggest.
Added prop-types to all instances of passing props to children in the front-end.
In cases in which props sometimes equal undefined or null, i set PropTypes.any (2 cases).
Browser, 
Npm Test

Added Prop-Types

---

client/src/AppContext.js
client/src/Components/LandingPage/LandingPage.js
client/src/Components/LandingPage/LogInBay.js

Upon changing the login field, or clicking signup, the Login error will now reset (disappear).
No Testing Yet

Login Error Reset

---

client/src/Components/LandingPage/FailedSignUpPopUp.css
client/src/Components/LandingPage/FailedSignUpPopUp.js
client/src/Components/LandingPage/FailedSignUpPopUp.less
client/src/Components/LandingPage/LogInBay.js

Fixed signup error positioning and Added disseapear feature when typing.
Local Testing

Signup-error-fix + Message reset

---

api/controllers/user_controller.js
api/routes.js
client/src/App.js
client/src/AppContext.js
client/src/Components/Nav/Nav.css
client/src/Components/Nav/Nav.js
client/src/Components/Nav/Nav.less
package.json

- Add a backend endpoint that receives a facebook id and sends back the countries data of the user associated with it.
- Un-hardcode and dev related urls and move to `.env` files.
- Code cleanup and comments
- Tested manually with REST client
- Did not add test for this endpoint as it is dependent on a facebook id. Test user's will (IIRC) expire so using one of their ID's will require updating the tests when they do. Using a real facebook accounts ID may not be a good idea for privacy reasons and should, at a minimum, acquire consent of the account owner.

Add backend endpoint to retrieve a friends countries

---

api/controllers/user_controller.js
api/routes.js
client/src/App.js
client/src/AppContext.js
client/src/Components/CountryPanel/CountryPanel.js
client/src/Components/Dashboard/Dashboard.js
client/src/Components/Map/Map.js
client/src/Components/Nav/Nav.css
client/src/Components/Nav/Nav.js
client/src/Components/Nav/Nav.less
package.json

- Populate dropdown menu with users facebook friends
- Show friends countries on map when a friend is selected
- Prevent CountryPanel from showing when viewing a friends map
- Render a header instead of dropdown for non-FB users
- Fix for #134 
- Code cleanup, comments and some necessary refactoring
- All existing tests continue to pass

Facebook - Show friends countries on map

---

api/routes.js
client/src/Components/LandingPage/Animation.css
client/src/Components/LandingPage/Animation.js
client/src/Components/LandingPage/Animation.less
client/src/Components/LandingPage/LandingPage.css
client/src/Components/LandingPage/LandingPage.less
client/src/Components/LandingPage/LandingPageSVG/airplanesvg.svg
client/src/Components/LandingPage/LandingPageSVG/cloud1.svg
client/src/Components/LandingPage/LandingPageSVG/cloud2.svg
client/src/Components/LandingPage/LandingPageSVG/cloud3.svg
client/src/Components/LandingPage/LandingPageSVG/cloud4.svg
client/src/Components/LandingPage/LogInBay.js

Created SVGs and animation of plane for the landing page. Adjusted the position of the login-bay.
Tested locally, current tests pass.

Landing Page Plane Animation

---

api/controllers/userController.js
api/routes.js
client/src/AppContext.js

Fixes needed to get FB auth working in deployment
This branch was deployed and tested manually in browser with FB test users. The live site now works with FB test users.

Facebook auth deployment fixes

---

__tests__/server.test.js
api/controllers/userController.js
api/routes.js
client/src/AppContext.js
client/src/Components/CountryBorder/CountryBorder.js
client/src/Components/Dashboard/Dashboard.js
client/src/Components/Map/countryStyles.js
client/src/Components/Nav/Nav.js
client/src/Components/Settings/Settings.css
client/src/Components/Settings/Settings.js
client/src/Components/Settings/Settings.less

- Add 'Reset Map' button and `/reset_user_map` endpoint to clear countries
- Close settings panel on map click
- Styling tweaks
- Code cleanup
- Added tests for `reset_user_map` endpoint
- Existing tests continue to pass

Reset Map functionality
